version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: esklp-mongo
    restart: unless-stopped
    ports:
      - "27318:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=esklpuser
      - MONGO_INITDB_ROOT_PASSWORD=6jwQpqreXTqJ

  dev:
    container_name: esklp-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb

  prod:
    container_name: esklp-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - mongodb


volumes:
  mongo_data:
