version: '3.8'

services:
  dev:
    container_name: esklp-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development

  prod:
    container_name: esklp-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
