version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: esklp-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  dev:
    container_name: esklp-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb

  prod:
    container_name: esklp-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - mongodb
