version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: esklp-mongo
    restart: unless-stopped
    ports:
      - "27318:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=esklpuser
      - MONGO_INITDB_ROOT_PASSWORD=6jwQpqreXTqJ
      - TZ=Europe/Moscow 

  dev:
    image: esklp-service
    container_name: esklp-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./log:/usr/src/app/log
      - ./ESKLP_download:/usr/src/app/ESKLP_download
    ports:
      - "3001:3001"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - TZ=Europe/Moscow
    depends_on:
      - mongodb

  prod:
    image: esklp-service
    container_name: esklp-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Moscow
    volumes:
      - ./log:/usr/src/app/log
      - ./ESKLP_download:/usr/src/app/ESKLP_download
    restart: unless-stopped
    depends_on:
      - mongodb


volumes:
  mongo_data:
